// <auto-generated />
namespace _21825470_CLCO_Assignment_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Minutes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Minutes));
        
        string IMigrationMetadata.Id
        {
            get { return "202203032016340_Minutes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
